spring:
  #RabbitMQ property set
  #  rabbitmq:
  #    host: 192.168.0.233
  #    port: 5672
  #    password: dev
  #    username: dev
  #    virtual-host: dev
  #    requested-heartbeat: 5
  #    listener:
  #      concurrency: 2
  #      max-concurrency: 5
  #      acknowledge-mode: manual
  #C3P0 property set
  c3p0:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    user: root
    password: 123456789
    acquireIncrement: 1
    initialPoolSize: 2
    maxIdleTime: 2
    maxPoolSize: 2
    minPoolSize: 2
    acquireRetryDelay: 1000
    acquireRetryAttempts: 60
    minPoolSizebreakAfterAcquireFailure: false
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      #      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy #1.4.X以前的配置
      naming: #1.4.X以后的配置
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    show-sql: true
server:
  port: 8082